
window.Media=(()=>{
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const status=(m,k="")=>{const e=$("mediaStatus");e.textContent=m;e.className="status "+k};
const blobData=blob=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)});
async function imageData(url){const r=await fetch(url);if(!r.ok)throw new Error("HTTP "+r.status);return blobData(await r.blob())}
async function searchTmdb(){const q=$("mediaQuery").value.trim();if(!q)return status("Введи название.","err");if(!APP.cfg.tmdb)return status("Добавь TMDB Bearer token в Настройки.","warn");status("Ищу в TMDB...");try{const r=await fetch("https://api.themoviedb.org/3/search/movie?query="+encodeURIComponent(q)+"&language=ru-RU&include_adult=false",{headers:{Authorization:"Bearer "+APP.cfg.tmdb}});if(!r.ok)throw new Error("TMDB HTTP "+r.status);const j=await r.json();renderMovies(j.results||[]);status("Найдено: "+(j.results?.length||0),"ok")}catch(e){status(e.message,"err")}}
function renderMovies(items){const w=$("mediaResults");$("mediaDetails").innerHTML="";w.innerHTML="";for(const m of items.slice(0,30)){const poster=m.poster_path?"https://image.tmdb.org/t/p/w500"+m.poster_path:"";const c=document.createElement("article");c.className="movie";c.innerHTML=(poster?'<img src="'+poster+'" alt="">':'<div class="empty" style="aspect-ratio:2/3">Нет постера</div>')+'<div class="movie-body"><div class="movie-title">'+esc(m.title||m.original_title)+'</div><div class="meta">'+esc((m.release_date||"").slice(0,4))+' · TMDB '+(m.vote_average?.toFixed?.(1)||"")+'</div><div class="movie-actions"><button class="btn details">Материалы</button>'+(poster?'<button class="btn add">В Studio</button>':"")+'</div></div>';qs(".details",c).onclick=()=>details(m.id);const a=qs(".add",c);if(a)a.onclick=async()=>{await Studio.addImage(await imageData(poster),"TMDB poster");APP.activate("studioView")};w.appendChild(c)}}
async function details(id){status("Загружаю материалы...");try{const H={Authorization:"Bearer "+APP.cfg.tmdb};const [dr,ir]=await Promise.all([fetch("https://api.themoviedb.org/3/movie/"+id+"?language=ru-RU",{headers:H}),fetch("https://api.themoviedb.org/3/movie/"+id+"/images?include_image_language=ru,en,null",{headers:H})]);if(!dr.ok||!ir.ok)throw new Error("TMDB details error");const d=await dr.json(),im=await ir.json();let fan=null;if(APP.cfg.fanart){try{const fr=await fetch("https://webservice.fanart.tv/v3.2/movies/"+id+"?api_key="+encodeURIComponent(APP.cfg.fanart));if(fr.ok)fan=await fr.json()}catch{}}renderDetails(d,im,fan);status("Материалы загружены.","ok")}catch(e){status(e.message,"err")}}
function art(url,label,meta=""){const c=document.createElement("div");c.className="art";c.innerHTML='<img src="'+url+'" alt=""><div class="meta">'+esc(label)+" "+esc(meta)+'</div><div style="padding:0 8px 8px"><button class="btn addArt" style="width:100%">Добавить в Studio</button></div>';qs(".addArt",c).onclick=async()=>{try{await Studio.addImage(await imageData(url),label);APP.activate("studioView")}catch(e){status("Изображение: "+e.message,"err")}};return c}
function renderDetails(d,im,fan){const w=$("mediaDetails");w.innerHTML='<div class="card"><h2>'+esc(d.title||d.original_title)+'</h2><div class="hint">'+esc(d.overview||"")+'</div></div>';const g=document.createElement("div");g.className="art-grid";for(const x of (im.posters||[]).slice(0,8))g.appendChild(art("https://image.tmdb.org/t/p/w500"+x.file_path,"TMDB poster",x.width+"×"+x.height));for(const x of (im.backdrops||[]).slice(0,8))g.appendChild(art("https://image.tmdb.org/t/p/w780"+x.file_path,"TMDB backdrop",x.width+"×"+x.height));for(const x of (im.logos||[]).slice(0,6))g.appendChild(art("https://image.tmdb.org/t/p/w500"+x.file_path,"TMDB logo",x.width+"×"+x.height));if(fan)for(const [type,list] of Object.entries(fan)){if(Array.isArray(list))for(const x of list.slice(0,4))if(x?.url)g.appendChild(art(x.url,"fanart.tv "+type,(x.width||"")+"×"+(x.height||"")))}w.appendChild(g)}
async function kinoriumSearch(){const q=$("mediaQuery").value.trim();if(!q)return status("Введи название.","err");status("Kinorium через Jina Search...");try{const h={Accept:"text/plain"};if(APP.cfg.jina)h.Authorization="Bearer "+APP.cfg.jina;const r=await fetch("https://s.jina.ai/"+encodeURIComponent(q)+"?site=ru.kinorium.com&site=kinorium.com",{headers:h});if(!r.ok)throw new Error("Jina HTTP "+r.status);showText("Kinorium search",await r.text());status("Готово.","ok")}catch(e){status(e.message,"err")}}
async function kinoriumParse(){const u=$("kinoriumUrl").value.trim();if(!/^https?:\/\//i.test(u))return status("Вставь полный URL Kinorium.","err");status("Читаю Kinorium...");try{const h={Accept:"text/plain","X-Respond-With":"text"};if(APP.cfg.jina)h.Authorization="Bearer "+APP.cfg.jina;const r=await fetch("https://r.jina.ai/"+u,{headers:h});if(!r.ok)throw new Error("Jina HTTP "+r.status);showText("Kinorium parser",await r.text());status("Готово.","ok")}catch(e){status(e.message,"err")}}
function showText(title,text){$("mediaResults").innerHTML="";$("mediaDetails").innerHTML='<div class="card"><h2>'+esc(title)+'</h2><div class="md">'+esc(text)+'</div></div>'}
$("tmdbSearchBtn").onclick=searchTmdb;$("kinoriumSearchBtn").onclick=kinoriumSearch;$("kinoriumParseBtn").onclick=kinoriumParse;$("mediaQuery").onkeydown=e=>{if(e.key==="Enter")searchTmdb()};
return{status};
})();
