
window.Studio=(()=>{
const stage=$("stage"),ctx=stage.getContext("2d"),workspace=$("workspace");
let nextId=1,generated=null,generatedPrompt="",scale=1;
const S={doc:{w:1280,h:720},tool:"select",layers:[],selected:null,brush:{size:14,color:"#ffffff"},hist:[],hi:-1,drag:null,draw:null};
const stat=(m,k="")=>{const e=$("studioStatus");e.textContent=m;e.className="status "+k};
const dataUrl=blob=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)});
const img=src=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src});
function fit(){const r=workspace.getBoundingClientRect();scale=Math.min((r.width-30)/S.doc.w,(r.height-30)/S.doc.h,1);if(!isFinite(scale)||scale<=0)scale=1;stage.style.width=Math.round(S.doc.w*scale)+"px";stage.style.height=Math.round(S.doc.h*scale)+"px";refreshStatus()}
function checker(){ctx.fillStyle="#dfe4ea";ctx.fillRect(0,0,stage.width,stage.height);for(let y=0;y<stage.height;y+=16)for(let x=0;x<stage.width;x+=16){ctx.fillStyle=((x/16+y/16)%2===0)?"#eef2f5":"#cfd6df";ctx.fillRect(x,y,16,16)}}
function textBounds(l){const t=document.createElement("canvas").getContext("2d");t.font=l.fontSize+"px Inter,system-ui,sans-serif";const a=String(l.text||"").split("\n");return{x:l.x,y:l.y,width:Math.max(...a.map(v=>t.measureText(v).width),1),height:a.length*Math.round(l.fontSize*1.18)}}
function drawLayer(l){if(!l.visible)return;ctx.save();ctx.globalAlpha=l.opacity;if(l.type==="image")ctx.drawImage(l.image,l.x,l.y,l.w,l.h);else if(l.type==="text"){ctx.font=l.fontSize+"px Inter,system-ui,sans-serif";ctx.fillStyle=l.color;ctx.textBaseline="top";let y=l.y;for(const line of String(l.text||"").split("\n")){ctx.fillText(line,l.x,y);y+=Math.round(l.fontSize*1.18)}}else if(l.type==="drawing")ctx.drawImage(l.canvas,0,0);ctx.restore()}
function render(){ctx.clearRect(0,0,stage.width,stage.height);checker();S.layers.forEach(drawLayer);const l=sel();if(l&&l.visible){const b=l.type==="text"?textBounds(l):{x:l.x,y:l.y,width:l.w,height:l.h};ctx.save();ctx.strokeStyle="#679cff";ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.strokeRect(b.x,b.y,b.width,b.height);ctx.restore()}}
function sel(){return S.layers.find(x=>x.id===S.selected)||null}
function select(id){S.selected=id;refreshUI();render()}
function serLayer(l){const c={id:l.id,type:l.type,name:l.name,visible:l.visible,opacity:l.opacity,x:l.x,y:l.y,w:l.w,h:l.h};if(l.type==="image")return{...c,src:l.src};if(l.type==="text")return{...c,text:l.text,fontSize:l.fontSize,color:l.color};if(l.type==="drawing")return{...c,data:l.canvas.toDataURL("image/png")};return c}
function snap(){return{doc:{...S.doc},selected:S.selected,nextId,layers:S.layers.map(serLayer)}}
async function restore(s){S.doc={...s.doc};S.selected=s.selected;nextId=s.nextId||1;S.layers=[];for(const l of s.layers){if(l.type==="image"){S.layers.push({...l,image:await img(l.src)})}else if(l.type==="text")S.layers.push({...l});else if(l.type==="drawing"){const im=await img(l.data),c=document.createElement("canvas");c.width=s.doc.w;c.height=s.doc.h;c.getContext("2d").drawImage(im,0,0);S.layers.push({...l,canvas:c})}}stage.width=S.doc.w;stage.height=S.doc.h;$("docWidth").value=S.doc.w;$("docHeight").value=S.doc.h;fit();render();refreshUI()}
function push(label){if(S.hi<S.hist.length-1)S.hist=S.hist.slice(0,S.hi+1);S.hist.push({label,s:snap()});S.hi=S.hist.length-1;historyUI()}
async function undo(){if(S.hi<=0)return;S.hi--;await restore(S.hist[S.hi].s);historyUI()}
async function redo(){if(S.hi>=S.hist.length-1)return;S.hi++;await restore(S.hist[S.hi].s);historyUI()}
function historyUI(){const w=$("historyList");w.innerHTML="";S.hist.forEach((h,i)=>{const d=document.createElement("div");d.className="history-item"+(i===S.hi?" current":"");d.textContent=h.label;w.appendChild(d)})}
async function addImage(src,name="Изображение"){const image=await img(src),k=Math.min(S.doc.w*.82/image.width,S.doc.h*.82/image.height,1),w=Math.round(image.width*k),h=Math.round(image.height*k);const l={id:nextId++,type:"image",name,visible:true,opacity:1,x:Math.round((S.doc.w-w)/2),y:Math.round((S.doc.h-h)/2),w,h,src,image};S.layers.push(l);select(l.id);push("Добавлен слой: "+name);render();refreshUI();return l}
function addText(){const text=window.prompt("Текст слоя","Новый текст")||"Новый текст";const l={id:nextId++,type:"text",name:"Текст",visible:true,opacity:1,x:100,y:100,w:320,h:80,text,fontSize:48,color:"#ffffff"};S.layers.push(l);select(l.id);push("Добавлен текст");render();refreshUI()}
function addDrawing(){const c=document.createElement("canvas");c.width=S.doc.w;c.height=S.doc.h;const l={id:nextId++,type:"drawing",name:"Кисть",visible:true,opacity:1,x:0,y:0,w:S.doc.w,h:S.doc.h,canvas:c};S.layers.push(l);select(l.id);push("Добавлен слой рисования");return l}
function duplicate(){const l=sel();if(!l)return;const s=serLayer(l);s.id=nextId++;s.name=l.name+" копия";if(l.type==="image")img(s.src).then(image=>{S.layers.push({...s,image,x:s.x+20,y:s.y+20});select(s.id);push("Дублирован слой");render();refreshUI()});else if(l.type==="drawing"){img(s.data).then(im=>{const c=document.createElement("canvas");c.width=S.doc.w;c.height=S.doc.h;c.getContext("2d").drawImage(im,0,0);S.layers.push({...s,canvas:c});select(s.id);push("Дублирован слой");render();refreshUI()})}else{S.layers.push({...s,x:s.x+20,y:s.y+20});select(s.id);push("Дублирован слой");render();refreshUI()}}
function remove(){const l=sel();if(!l)return;S.layers=S.layers.filter(x=>x.id!==l.id);S.selected=S.layers.at(-1)?.id||null;push("Удалён слой");render();refreshUI()}
function layersUI(){const w=$("layerList");w.innerHTML="";if(!S.layers.length){w.innerHTML='<div class="hint">Слоёв нет.</div>';return}[...S.layers].reverse().forEach(l=>{const r=document.createElement("div");r.className="layer-item"+(l.id===S.selected?" active":"");const eye=document.createElement("button");eye.className="mini";eye.textContent=l.visible?"👁":"🚫";eye.onclick=e=>{e.stopPropagation();l.visible=!l.visible;push(l.visible?"Слой показан":"Слой скрыт");render();layersUI()};const m=document.createElement("div");m.innerHTML='<div class="layer-name">'+escapeHtml(l.name)+'</div><div class="layer-type">'+l.type+'</div>';const a=document.createElement("div"),up=document.createElement("button"),dn=document.createElement("button");up.className=dn.className="mini";up.textContent="↑";dn.textContent="↓";up.onclick=e=>{e.stopPropagation();const i=S.layers.indexOf(l);if(i<S.layers.length-1){[S.layers[i],S.layers[i+1]]=[S.layers[i+1],S.layers[i]];push("Слой поднят");render();layersUI()}};dn.onclick=e=>{e.stopPropagation();const i=S.layers.indexOf(l);if(i>0){[S.layers[i],S.layers[i-1]]=[S.layers[i-1],S.layers[i]];push("Слой опущен");render();layersUI()}};a.append(up,dn);r.append(eye,m,a);r.onclick=()=>select(l.id);w.appendChild(r)})}
function propsUI(){const l=sel();$("noSelection").classList.toggle("hidden",!!l);$("propertiesPanel").classList.toggle("hidden",!l);if(!l)return;$("propName").value=l.name;$("propX").value=Math.round(l.x);$("propY").value=Math.round(l.y);$("propWidth").value=Math.round(l.w);$("propHeight").value=Math.round(l.h);$("propOpacity").value=l.opacity;$("textProps").classList.toggle("hidden",l.type!=="text");if(l.type==="text"){$("propText").value=l.text;$("propFontSize").value=l.fontSize;$("propTextColor").value=l.color}}
function refreshStatus(){$("leftStatus").textContent="Инструмент: "+(S.tool==="select"?"выбор":"кисть");$("rightStatus").textContent=S.doc.w+" x "+S.doc.h+" | "+Math.round(scale*100)+"%"}
function refreshUI(){layersUI();propsUI();refreshStatus()}
function point(e){const r=stage.getBoundingClientRect();return{x:(e.clientX-r.left)*stage.width/r.width,y:(e.clientY-r.top)*stage.height/r.height}}
function hit(p){for(let i=S.layers.length-1;i>=0;i--){const l=S.layers[i];if(!l.visible)continue;if(l.type==="drawing"){const d=l.canvas.getContext("2d").getImageData(Math.max(0,Math.floor(p.x)),Math.max(0,Math.floor(p.y)),1,1).data;if(d[3]>10)return l;continue}const b=l.type==="text"?textBounds(l):{x:l.x,y:l.y,width:l.w,height:l.h};if(p.x>=b.x&&p.x<=b.x+b.width&&p.y>=b.y&&p.y<=b.y+b.height)return l}return null}
stage.onpointerdown=e=>{const p=point(e);stage.setPointerCapture(e.pointerId);if(S.tool==="select"){const l=hit(p);if(l){select(l.id);S.drag={id:l.id,dx:p.x-l.x,dy:p.y-l.y}}else select(null)}else{let l=sel();if(!l||l.type!=="drawing")l=addDrawing();const b=l.canvas.getContext("2d");b.strokeStyle=S.brush.color;b.lineWidth=S.brush.size;b.lineCap="round";b.lineJoin="round";b.beginPath();b.moveTo(p.x,p.y);S.draw={id:l.id};render()}};
stage.onpointermove=e=>{const p=point(e);if(S.drag){const l=S.layers.find(x=>x.id===S.drag.id);if(l){l.x=Math.round(p.x-S.drag.dx);l.y=Math.round(p.y-S.drag.dy);render();propsUI()}}else if(S.draw){const l=S.layers.find(x=>x.id===S.draw.id);if(l){const b=l.canvas.getContext("2d");b.lineTo(p.x,p.y);b.stroke();render()}}};
stage.onpointerup=()=>{if(S.drag){S.drag=null;push("Перемещён слой");refreshUI()}if(S.draw){S.draw=null;push("Рисование");refreshUI()}};
async function generate(){const p=$("prompt").value.trim();if(!p)return stat("Введи промпт.","err");const b=$("generateBtn");b.disabled=true;b.textContent="Генерация...";stat("Puter AI...");try{const [rw,rh]=$("ratio").value.split(":").map(Number);const el=await puter.ai.txt2img(p,{model:$("model").value,quality:$("quality").value,ratio:{w:rw,h:rh},test_mode:$("testMode").checked});generated=el.src;generatedPrompt=p;$("previewBox").innerHTML="";$("previewBox").appendChild(el);$("addGeneratedBtn").disabled=false;$("downloadBtn").disabled=false;await addImage(generated,"AI: "+p.slice(0,26));stat("Готово. Добавлено как слой.","ok")}catch(e){stat("Ошибка: "+(e?.message||e?.msg||String(e)),"err")}finally{b.disabled=false;b.textContent="Сгенерировать и добавить как слой"}}
$("generateBtn").onclick=generate;$("addGeneratedBtn").onclick=()=>generated&&addImage(generated,"AI: "+generatedPrompt.slice(0,26));$("downloadBtn").onclick=()=>{if(!generated)return;const a=document.createElement("a");a.href=generated;a.download="ai-result.png";a.click()};
$("reference").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;await addImage(await dataUrl(f),f.name);e.target.value=""};$("addTextBtn").onclick=addText;$("duplicateLayerBtn").onclick=duplicate;$("deleteLayerBtn").onclick=remove;$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;$("fitBtn").onclick=fit;
$("exportBtn").onclick=()=>{render();const a=document.createElement("a");a.href=stage.toDataURL("image/png");a.download="skooma-studio.png";a.click()};$("clearBtn").onclick=()=>{if(confirm("Удалить все слои?")){S.layers=[];S.selected=null;push("Холст очищен");render();refreshUI()}};
$("resizeDocBtn").onclick=()=>{const w=Math.max(64,+$("docWidth").value||1280),h=Math.max(64,+$("docHeight").value||720),ow=S.doc.w,oh=S.doc.h;S.doc={w,h};stage.width=w;stage.height=h;for(const l of S.layers)if(l.type==="drawing"){const old=l.canvas,c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(old,0,0,ow,oh,0,0,w,h);l.canvas=c;l.w=w;l.h=h}fit();push("Размер документа изменён");render();refreshUI()};
$("applyPropsBtn").onclick=()=>{const l=sel();if(!l)return;l.name=$("propName").value.trim()||l.name;l.x=+$("propX").value||0;l.y=+$("propY").value||0;l.opacity=+$("propOpacity").value;if(l.type!=="drawing"){l.w=Math.max(1,+$("propWidth").value||l.w);l.h=Math.max(1,+$("propHeight").value||l.h)}if(l.type==="text"){l.text=$("propText").value;l.fontSize=Math.max(8,+$("propFontSize").value||48);l.color=$("propTextColor").value}push("Свойства изменены");render();refreshUI()};
$("brushColor").oninput=e=>S.brush.color=e.target.value;$("brushSize").oninput=e=>{$("brushSizeValue").textContent=e.target.value;S.brush.size=+e.target.value};qsa(".tool-btn").forEach(b=>b.onclick=()=>{qsa(".tool-btn").forEach(x=>x.classList.remove("primary"));b.classList.add("primary");S.tool=b.dataset.tool;refreshUI()});
window.addEventListener("resize",fit);window.addEventListener("keydown",e=>{const m=e.ctrlKey||e.metaKey;if(m&&e.key.toLowerCase()==="z"&&!e.shiftKey){e.preventDefault();undo()}else if((m&&e.key.toLowerCase()==="y")||(m&&e.shiftKey&&e.key.toLowerCase()==="z")){e.preventDefault();redo()}else if(e.key==="Delete")remove()});
stage.width=S.doc.w;stage.height=S.doc.h;fit();render();push("Начальное состояние");refreshUI();
return{fit,addImage};
})();
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
